name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Docker build
      run: docker build . -t hannut1/cicd-demo --platform linux/amd64
    - name: Docker push
      run: |
        docker login -u hannut1 -p ${{ secrets.DOCKER_PASSWORD }}
        docker push hannut1/cicd-demo
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ec2-52-78-89-144.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          docker pull hannut1/cicd-demo
          docker stop server
          docker run -d --rm --name server -p 80:3000 hannut1/cicd-demo
